### ISSUE TITLE
About the baselines

### ISSUE THREAD

**Issue by lucasliunju** [kongds/MoRA#4]
Hi, thanks for your great work.

I would like to use the same codebase to compare MoRA and LoRA. So, I would like to ask whether I can use this code to run LoRA and then analyze the difference between LoRA and MoRA.

Thanks!

**Comment by kongds** [comment]
Thanks for your interest in our work.  
Our code is compatible with LoRA and other variants.

**Comment by kongds** [comment]
Thanks for your advice. However, I currently don’t have plans to test MoRA on code due to my unfamiliarity with that area.
