### ISSUE TITLE
Document mora_type

### ISSUE THREAD

**Issue by winglian** [kongds/MoRA#6]
Can you add more flavor about what each mora_type value means or refers to in the paper? The is pretty opaque currently and might be best handled by using enums for mora_type.

**Comment by winglian** [comment]
1 & 6 are defined in the readme as
```
    # type 1 (Sharing) for large lora ranks, Eq. 6 in paper
    # type 6 (RoPE based) for small lora ranks, Eq. 9 in paper
```
but there are several places in the code where it is compared to values 2, 3, or 4.

**Comment by kongds** [comment]
Thanks for your advice.

Types 2, 3, and 4 use sharing like Type 1, but with different share groups. They are used for ReMoRA, which merges MoRA and changes its types to increase rank of delta w by different share groups. https://github.com/kongds/MoRA/blob/0ff64b144e60b54fe7c0ff7b4e76c99c949e923d/train.py#L64-L70
