### ISSUE TITLE
unused code 

### ISSUE THREAD

**Issue by winglian** [kongds/MoRA#7]
there are several places where this is defined
```python
mm, nn = m*mr, n * nr
```

but those variables aren't ever used. Is this a signal the implementation is incorrect or can they be safely removed?

**Comment by kongds** [comment]
It can be safely removed.

The following code is used to split `x` into `x[..., :mm]` and `x[..., mm:]`:
```python 
mr, nr = in_f // r + 1, in_f // r
m, n = in_f - r * nr, r * mr - in_f
mm, nn = m * mr, n * nr
```
This ensures that we can use code like the following to reduce the dimension of `x` from `in_f` to `r = mr + nr`:
[https://github.com/kongds/MoRA/blob/0ff64b144e60b54fe7c0ff7b4e76c99c949e923d/peft-mora/src/peft/tuners/lora/layer.py#L251-L253](https://github.com/kongds/MoRA/blob/0ff64b144e60b54fe7c0ff7b4e76c99c949e923d/peft-mora/src/peft/tuners/lora/layer.py#L251-L253)
