### ISSUE TITLE
Integrate into torchtune

### ISSUE THREAD

**Issue by impredicative** [kongds/MoRA#8]
[torchtune](https://github.com/pytorch/torchtune) is a native-PyTorch library for LLM fine-tuning.

With regard to integrating MoRA into torchtune, please refer to this discussion: https://github.com/pytorch/torchtune/discussions/1043

**Comment by kongds** [comment]
Thanks for your interest in our method.

For the different types of MoRA in discussion, we only use the 1 and 6 flags. The types like 2, 3, and 4 are internally used for ReMoRA to change types of sharing groups during training.

**Comment by kongds** [comment]
Thanks for the advice. 
I admit torchtune is a convenient tool for fine-tuning LLMs, but I am not familiar with it.
Additionally, we have provided a customized PEFT library that includes MoRA in our repository, which is compatible with previous peft training scripts.
