### ISSUE TITLE
Incorrect LoRa init

### ISSUE THREAD

**Issue by catid** [kongds/MoRA#9]
The initialization for LoRa is not very good:

https://github.com/kongds/MoRA/blob/0ff64b144e60b54fe7c0ff7b4e76c99c949e923d/peft-mora/src/peft/tuners/lora/layer.py#L723

This should be:

```
        std_dev = 1 / torch.sqrt(torch.tensor(rank).float())
        self.lora_A = nn.Parameter(torch.randn(d_out, rank)*std_dev)
        self.lora_B = nn.Parameter(torch.zeros(rank, d_in))
```

**Comment by catid** [comment]
You should find it trains about 2x faster, perhaps the results will be significantly different compared to your MoRa idea

**Comment by kongds** [comment]
The LoRA implementation is directly from `peft`. You can find the same lines in [this link](https://github.com/huggingface/peft/blob/03798a9143c90d796a0bee8f43863668d084381f/src/peft/tuners/lora/layer.py#L573-L574). If you find the initialization is not good, please create an issue in `peft`.

Moreover, these lines are used for adding LoRA to the `embedding` module, but we are not adding LoRA to `embedding`.

**Comment by catid** [comment]
Ah I see yeah that function does the right thing.
